name: crosstool-NG

on:
  pull_request:
    paths:
      - crosstool/**
      - .github/workflows/crosstool.yaml
  push:
    branches:
      - main
    paths:
      - crosstool/**
      - .github/workflows/crosstool.yaml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'duhow' }}
    steps:
      - uses: actions/checkout@v2
      - name: Login GHCR
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}-crosstool:latest
          context: crosstool/
